### ISSUE TITLE
Teknoparrot error 0x80040154

### ISSUE THREAD

**Issue by iammedude** [teknogods/OpenParrot#217] opened 2023-01-23 00:20 UTC
Whenever im trying to play wmmt6, I get the error 0x80040154. I don't have any windows 7 files backed up and I'm only on windows 10 no other versions of windows.

**Comment by nzgamer41** [comment] 2023-01-23 05:04
Closing issue, this is a windows issue and not caused by OpenParrot. If you are sure it's not your computer, take a screenshot and reply with it.

**Closed by nzgamer41** 2023-01-23 05:04 UTC

**Comment by iammedude** [comment] 2023-01-24 00:07
![image](https://user-images.githubusercontent.com/123291431/214180338-32f07174-94dc-4028-a883-764a9be4279b.png)

**Comment by nzgamer41** [comment] 2023-01-24 00:10
duplicate of #345

**Comment by nzgamer41** [comment] 2023-01-24 00:10
https://github.com/teknogods/TeknoParrotUI/issues/345
