### ISSUE TITLE
Dreamraiders

### ISSUE THREAD

**Issue by Kraakie256** [teknogods/OpenParrot#284] opened 2024-05-13 19:31 UTC
Teknoparrot version 10.0.1261

Assigend buttons (Keyboard) do not work.
Only working button is the assinged test button

Start button in my case the spacebar does not start the game.

**Comment by Pete-McDonald** [comment] 2024-06-17 09:48
It's fine here on 1.0.0.1269 using rawinput

![image](https://github.com/teknogods/OpenParrot/assets/82280111/b609c180-cfb9-421e-820e-bd33036545e3)

**Comment by Daren76** [comment] 2024-06-17 10:03
I've done the same. I've set it to raw input and can use my right button on my sinden light gun to start the game. Try running TP as administrator.

**Comment by romadu** [comment] 2024-06-17 10:14
> It's fine here on 1.0.0.1269 using rawinput
> 
> ![image](https://private-user-images.githubusercontent.com/82280111/340262057-b609c180-cfb9-421e-820e-bd33036545e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTk1MjksIm5iZiI6MTcxODYxOTIyOSwicGF0aCI6Ii84MjI4MDExMS8zNDAyNjIwNTctYjYwOWMxODAtY2ZiOS00MjFlLTgyMGUtYmQzMzAzNjU0NWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NWMxZDViYjZhZDAzMDliYWU4ZGQyZWRhMWU2MDUyODQ5NDYzY2NhYTM4YTJlMWM1ZjM3OGM3MTU4OTU4OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b5cCGajqCpIaPOuJNxV6glyPk9c3Sgw1TRxHfOOe6Cs)

 Running on Win11 and recent intel cpu?

**Comment by romadu** [comment] 2024-06-17 10:24
> I've done the same. I've set it to raw input and can use my right button on my sinden light gun to start the game. Try running TP as administrator.

Tried running TP as administrator, but still can't start.

**Comment by Daren76** [comment] 2024-06-17 15:29
Try changing PCB region and Dongle region to USA. Worth a try.

**Comment by romadu** [comment] 2024-06-18 01:20
> Try changing PCB region and Dongle region to USA. Worth a try.

Thanks for the suggestion. Changing PCB region and Dongle region didn’t enable Start button to start the game. Afaik it’s set to Japan so Test Mode calibration settings will save.

I will try installing SDK and trying to trace dependencies and version details for DLL to try to identify the conflict or issue. It’s definitely not TP or dump files related, some other issue that’s not easy to identify. If anyone has any suggestions for troubleshooting with those tools, that would be greatly appreciated.

**Comment by romadu** [comment] 2024-06-20 03:12
It seems that the issue with Dream Raiders not progressing past the demo screen because Start button is not recognised could be due to a recent Windows update that causes a conflict with a codec or driver. Is it possible to create a patch to ensure that the required version of the driver can be used by Dream Raiders?

**Comment by romadu** [comment] 2024-06-27 04:30
I can confirm that Dream Raiders start button works on Windows 10 OS version 19045.3803 and Windows Experience 1000.19051.1000. However, it does not work on Windows 10 OS version 19045.4929 and Windows Experience 1000.19058.1000.

I don't know what has specifically changed that prevents the Start button to work on Dream Raiders demo screen, but Dream Raiders doesn't current work on latest Windows 10 and Windows 11.

**Comment by legend800** [comment] 2024-06-27 06:10
Works fine here. Win11 22621.3007, latest Teknoparrot version

**Comment by romadu** [comment] 2024-06-27 06:37
> Works fine here. Win11 22621.3007, latest Teknoparrot version

However, it doesn't work for me on Win11 22631.3737, latest Teknoparrot version

**Comment by jcstahl1** [comment] 2024-06-27 12:45
Also works fine here with latest TP on Win11 22631.3810 and Win10 19045.4929

**Comment by Boomslangnz** [comment] 2024-07-20 07:12
I have pushed fix for start button issue etc, could you confirm if inputs are good for everyone now?

**Comment by jcstahl1** [comment] 2024-07-20 13:56
all good here

**Comment by Georgie-SBH** [comment] 2024-07-20 14:13
Works great here as well now

**Comment by romadu** [comment] 2024-07-20 14:13
Working for me with both xinput and rawinput. Many thanks for resolving the issue!

**Comment by Boomslangnz** [comment] 2024-07-20 16:34
Great, thanks guys. Will close this issue now :)

**Closed by Boomslangnz** 2024-07-20 16:34 UTC
